#define __WON_MASTER_CPP__
#include "DetectFirewallOp.cpp"
#include "FindPatchOp.cpp"
#include "FTPGetOp.cpp"
//#include "GameSpySupport.cpp"
#include "GetMOTDOp.cpp"
#include "GetVersionOp.cpp"
#include "HTTPGetOp.cpp"
#include "MediaMetrix.cpp"
