#include "ButtonConfig.cpp"
#include "ComboBoxConfig.cpp"
#include "ComponentConfig.cpp"
#include "ContainerConfig.cpp"
#include "DialogConfig.cpp"
#include "FontConfig.cpp"
#include "GUIConfig.cpp"
#include "ImageButtonConfig.cpp"
#include "ImageConfig.cpp"
#include "InputBoxConfig.cpp"
#include "LabelConfig.cpp"
#include "ListBoxConfig.cpp"
#include "MenuConfig.cpp"
#include "MSComponentConfig.cpp"
#include "MultiListBoxConfig.cpp"
#include "ResourceConfig.cpp"
#include "ScrollAreaConfig.cpp"
#include "ScrollbarConfig.cpp"
#include "SimpleComponentConfig.cpp"
#include "SplitterConfig.cpp"
#include "TabCtrlConfig.cpp"
#include "TextBoxConfig.cpp"
#include "TreeCtrlConfig.cpp"

#ifdef _DEBUG
#include "WinSkin.cpp"
#endif

#include "WONControlsConfig.cpp"
#include "WONGUIConfig.cpp"
